### ISSUE TITLE
疫苗之亡：中国人最绝望的一天

### ISSUE THREAD

**Issue by IchiroArisugawa** [Terminus2049/Terminus2049.github.io#144]
[疫苗之亡：中国人最绝望的一天.docx](https://github.com/Terminus2049/Terminus2049.github.io/files/2216748/default.docx)
来源：https://mp.weixin.qq.com/s/NYJ_MIms7a3XTJawpLfhhw
 暂未404，但是提供大量有效信息，可收录

**Comment by pigeon-lift** [comment]
你好 我是路透社的一名记者 叫 Huizhong Wu。 我想了解现在这个proejct的情况，咱们可以联系吗？
