### ISSUE TITLE
【404】看不到的焦虑和看得到的质疑，北大 120 年校庆见闻

### ISSUE THREAD

**Issue by b614103080** [Terminus2049/Terminus2049.github.io#25]
https://www.douban.com/note/668704367/

只有豆瓣日記存活，網站上的已經沒了

**Comment by cmmei** [comment]
https://webcache.googleusercontent.com/search?q=cache:DoBCgWsuf6wJ:https://www.qdaily.com/articles/52934.html+&amp;cd=1&amp;hl=ja&amp;ct=clnk&amp;gl=jp

**Comment by cmmei** [comment]
Google cache
