### ISSUE TITLE
谷歌是不是对 GitHub Page有偏见

### ISSUE THREAD

**Issue by tsai1993** [Terminus2049/Terminus2049.github.io#4]
搜索“对岳同学事件中五个问题的看法”，居然是这个网站排名靠前。
https://p2p-terminus.hashbase.io

**Comment by cmmei** [comment]
哈哈哈。试了一下 Duckduckgo 就不会。

**Comment by b614103080** [comment]
我这边用google，第一条是PKU BBS...https://bbs.pku.edu.cn/v2/post-read.php?bid=64&threadid=16398052
