### ISSUE TITLE
 重磅消息！富士康工人声援尘肺病工人维权！

### ISSUE THREAD

**Issue by b614103080** [Terminus2049/Terminus2049.github.io#42]
https://www.shidaixianfeng.tk/archives/5576

**Comment by cmmei** [comment]
在简书上发......分分钟

湖南尘肺工人：贡献青春，却被抛弃；理性维权，反遭打压！https://www.jianshu.com/p/340dfe73ca48?utm_campaign=maleskine&utm_content=note&utm_medium=seo_notes&utm_source=recommendation
