### ISSUE TITLE
据南华早报报道 该项目维护者两人被监视居住 一人仍下落不明

### ISSUE THREAD

**Issue by larvata** [Terminus2049/Terminus2049.github.io#597]
来源:
https://www.scmp.com/news/china/politics/article/3081569/chinese-activists-detained-after-sharing-censored-coronavirus

以下是该报道相关内容的翻译:

## 中国活动人士因分享被屏蔽的肺炎相关信息而被拘留

- 据相关的人士透露，当事人现因寻衅滋事为由被监视居住。

- 三名当事人曾维护一个致力于保存被审查内容的项目。

陈玫、蔡伟以及蔡伟的唐姓女友三人，从2018年开始维护一个名为端点星的项目。该项目致力于保存因言论审查而被删除的网页(被审查的内容)。

微软的Github网站是一个用来为程序员提供协作开发的服务，现在也被越来越多的中国活动人士用来发布被审查的内容。

除端点星外，Github上还有一些项目也致力于保存肺炎相关的文章以及从主流媒体和社交网络上采集到的信息。其中一些项目的维护者表示他们希望藉此让公众"更好地了解疫情以及疫情影响下的人们的生活"。

端点星的主页已于周六(4月25日)被屏蔽。

因担心报复而不愿透露姓名知情者告诉南华早报，三名北京的志愿者于4月19日失踪，他们的家人和朋友曾联系警方，但警方并未透露三人的下落。
知情者同时透露"大约5天后，蔡和唐的家人收到了从朝阳派出所发来的通知"，"起初的几天警方并不承认抓捕了他们"

根据警方的通知，蔡和唐因寻衅滋事而被监视居住。陈的家人至今还未收到官方的通知。
"他们会定期和家人和朋友联络，失联后，令他们的家人和朋友极度不安"。

至发稿时记者(南华早报)未能联络到朝阳派出所。

**Comment by isblue01** [comment]
wtf?

**Comment by cirosantilli** [comment]
This Chinese RFA article gives the Chinese names of the detained and some background on them: https://www.rfa.org/mandarin/Xinwen/7-04252020144555.html and it gives the name of the third detainee: 小唐, who is also Cai Wei girlfriend.

I would like to understand though how their identities were found: https://github.com/Terminus2049/Terminus2049.github.io/issues/598
