### ISSUE TITLE
该项目的描述存在一个误区

### ISSUE THREAD

**Issue by GTX-GSO** [Terminus2049/Terminus2049.github.io#601]
即 <strong>注</strong>：“端点星暂不收录未被中国政府和谐的内容。”

先说结论，<strong>被相关平台删除的贴子!=被中国政府和谐的内容</strong>

我国的网警主要指公安部11局，以及其下属的省市级别网络与信息安全通报中心为主要职能承载单位，在2020年6月1日起生效的《网络安全审查办法》第十八条规定“运营者应当督促产品和服务提供者履行网络安全审查中作出的承诺，网络安全审查办公室通过接受举报等形式加强事前事中事后监督。”

换句话讲，国内的网络审查主要体现在**立项审查**上，具体细化到执行方面比较类似于大家都接触过的域名备案，而对于舆论事件的审查主要依赖于被动监测，即互联网媒体平台提供方通报、工信部12377.cn举报，不会也没有能力进行多平台大范围的舆论筛查。

_（朋友曾在hz市级网信中心供职，编制仅16人，有合作承标公司，无外聘职位，工作不限于政治内容，黄赌毒欺诈暴恐侵权谣言全在范畴内，由此推测全国网警规模也不难得出类似结论）_

而大多数的删帖、控评、限流等网站内容筛查**本质是一种资本的自保行为**，多采用算法+平台内举报+人工的模式对敏感内容即时甄别与排除。

平台内容对平台自身的影响，我举个显而易见的例子，18年7月20号官媒点名批评B站含有大量低俗内容，责令APP下架整改，隔夜其公司美股收盘跌逾4%，随后网站视频审核变的极为严苛，不但关闭任何政治类视频评论，<s>甚至禁止评论与蛤蟆相关的视频</s>还彻查了过去所有的稿件，<s>连同本人14年上传的游戏视频也被退稿</s>

所以把国内过于严苛的内容筛查并归结于政府的和谐是不恰当的，我支持端点星项目的出发点与积极意义，但我更希望它能像WIKI一样客观中立不带政治倾向，也希望你们可以选择更为恰当的表述

**Comment by larvata** [comment]
我认为你这个说法有问题
把`被中国政府和谐的内容`定义为`被中国政府删除的内容`是对原义的曲解
`被中国政府和谐的内容`不是技术层面的 而是事实层面的

大多数情况下 中国政府当然不会主动下指令要求删除某些内容 因为他们有更高效的方法 即`自我审查`
鉴于中国政府对国内企业的控制能力 只要给一些暗示 那么企业自然会按照政府期望的目标去执行
企业为了生存 不得不配合中国政府的意图
你上文举的关于B站的例子也印证了这一点

我这还可以提供另外一个思路佐证我的观点
假如在海外网站上发布相同的内容结果应该是什么?
按照你的理解 因为删除那些内容只是中国企业的行为 那么你在海外网站发表的相同内容应该不受影响
然而事实却是 你有大概率会接到当地片警的电话 让你删一些内容 甚至直接上门带你去他们那儿 并留让你下一份保证书

警察是谁找来的 又是谁在监控你的海外言论 当然不会是那些互联网企业
那么到底是谁删的 这不显而易见

**Comment by GTX-GSO** [comment]
我上文举例的B站被央媒点名的原因并不是任何反动、反共内容，而是因为色情及乱伦动画，且我的本意是B站对于政治性内容过于苛刻的自查并非来自“中央指示”，是一种over react，同样题材的内容在其他国内平台可以上传但是在治理后的B站就不行，而把政府看作一个有意识且邪恶的组织并赋予其人的特性这就有点Republican Party的意思了，人们本能的会把不理解其运作体系的组织具象化这是源于对未知的恐惧，但是如果你仔细了解一下网警的编制及其工作范畴，不难发现它就是基于举报系统运作的，12377.cn接收举报信息，逐级下放到各片区，民警负责约谈及思想工作，情节严重的给予行政拘留。
所以如果事实求是一点说，端点星收录的删除文章，随便一查就会发现有大量的与事实不符且带有倾向性的内容（并非全部），随便拿出来一篇比如泉州欣佳酒店，百度百科上都写明了死亡人数，但是文章却说中国政府控制媒体不给报道任何死亡信息，这难道也算客观吗
[https://baike.baidu.com/item/%E6%B3%89%E5%B7%9E%E6%AC%A3%E4%BD%B3%E9%85%92%E5%BA%97/24516657？fromtitle=%E6%AC%A3%E4%BD%B3%E9%85%92%E5%BA%97&fromid=24516711&fr=aladdin](url)

**Comment by GTX-GSO** [comment]
我上文举例的B站被央媒点名的原因并不是任何反动、反共内容，而是因为色情及乱伦动画，且我的本意是B站对于政治性内容过于苛刻的自查并非来自“中央指示”，是一种over react，同样题材的内容在其他国内平台可以上传但是在治理后的B站就不行，而把政府看作一个有意识且邪恶的组织并赋予其人的特性这就有点Republican Party的意思了，人们本能的会把不理解其运作体系的组织具象化这是源于对未知的恐惧，但是如果你仔细了解一下网警的编制及其工作范畴，不难发现它就是基于举报系统运作的，12377.cn接收举报信息，逐级下放到各片区，民警负责约谈及思想工作，情节严重的给予行政拘留。

所以如果事实求是一点说，端点星收录的删除文章，随便一查就会发现有大量的与事实不符且带有倾向性的内容（并非全部），随便拿出来一篇比如泉州欣佳酒店，百度百科上都写明了死亡人数，但是文章却说中国政府控制媒体不给报道任何死亡信息，这难道也算客观吗
[https://baike.baidu.com/item/%E6%B3%89%E5%B7%9E%E6%AC%A3%E4%BD%B3%E9%85%92%E5%BA%97/24516657？fromtitle=%E6%AC%A3%E4%BD%B3%E9%85%92%E5%BA%97&fromid=24516711&fr=aladdin](url)

**Comment by GTX-GSO** [comment]
我承认中国是一个集权国家，但并非一个极权国家，你不能因为不了解其运作机制就把他凭空想象成like hivemind，我前面也分析过CCP没有也没有能力分配大量人力在外网进行普遍的言论筛查，因为这本就是不现实的事情，我倒希望你能找出例子来证明我是错的，不然那就是其他中国人对你的overseas comment感到不爽所以选择了举报。

我也不是什么小粉红，我一样喜欢膜蛤，习近平取消连任限制的时候我甚至在学校写过骂街长文，但这都改变不了一个事实那就是既然我选择了留在国内，那么CCP连同中国，与你的个人发展是positive correlation，不会真的有人幼稚到认为CCP如果倒台放权，大陆的意识型态转变成台湾国（非贬义）or HK，你的个人发展会有任何积极的变化把？

但是端点星可以有许多积极意义，比如揭露地方政府的官官相护层层包庇，培养另一种角度的独立思考能力，我不清楚这个项目的初衷是怎么样的，但我不愿意看到它变成一个披着相对客观外皮的极右主义根据地。

**Comment by larvata** [comment]
所以总结一下你的观点是: 文章是平台所删 非政府主导行为
我们看到的事实是: 端点星备份了`被平台所删的文章` 平台没有动作 反而中国政府把人抓了

你的观点合逻辑吗?

**Comment by GTX-GSO** [comment]
我的观点：端点星收录不实文章→引起他人不满→12377.cn接收举报→调查网站负责人→下放到片区→行政拘留
而不是“黑暗的政府一手遮天组建了强大的网络警察每天翻找github在内的世界所有互联网站点寻找敏感言论”
我相信你的阅读理解能力，但如果你选择偷换概念而不是拿出合理的论据反驳我，那也就当我没说过吧

**Comment by larvata** [comment]
这个是你对这个issue的描述 摘录重点内容如下

> 先说结论，**被相关平台删除的贴子!=被中国政府和谐的内容**

> 换句话讲，国内的网络审查主要体现在**立项审查**上，具体细化到执行方面比较类似于大家都接触过的域名备案，而对于舆论事件的审查主要依赖于被动监测，即互联网媒体平台提供方通报、工信部12377.cn举报，不会也没有能力进行多平台大范围的舆论筛查。

> 而大多数的删帖、控评、限流等网站内容筛查**本质是一种资本的自保行为**，多采用算法+平台内举报+人工的模式对敏感内容即时甄别与排除。

> 所以把国内过于严苛的内容筛查并归结于政府的和谐是不恰当的，我支持端点星项目的出发点与积极意义，但我更希望它能像WIKI一样客观中立不带政治倾向，也希望你们可以选择更为恰当的表述

----

概括一下就是我上文反驳的观点 即 **删除文章和政府无关 是平台行为**

之后的讨论我想也应该围绕这点

如果你还想另外讨论端点星是怎么没的 可以另开一个issue

**Comment by GTX-GSO** [comment]
> 这个是你对这个issue的描述 摘录重点内容如下
> 
> > 先说结论，**被相关平台删除的贴子!=被中国政府和谐的内容**
> 
> > 换句话讲，国内的网络审查主要体现在**立项审查**上，具体细化到执行方面比较类似于大家都接触过的域名备案，而对于舆论事件的审查主要依赖于被动监测，即互联网媒体平台提供方通报、工信部12377.cn举报，不会也没有能力进行多平台大范围的舆论筛查。
> 
> > 而大多数的删帖、控评、限流等网站内容筛查**本质是一种资本的自保行为**，多采用算法+平台内举报+人工的模式对敏感内容即时甄别与排除。
> 
> > 所以把### **国内**过于严苛的内容筛查并归结于政府的和谐是不恰当的，我支持端点星项目的出发点与积极意义，但我更希望它能像WIKI一样客观中立不带政治倾向，也希望你们可以选择更为恰当的表述
> 
> 概括一下就是我上文反驳的观点 即 **删除文章和政府无关 是平台行为**
> 
> 之后的讨论我想也应该围绕这点
> 
> 如果你还想另外讨论端点星是怎么没的 可以另开一个issue

帮你标注了国内两个字以防你看不到，github也属于国内平台受国家监管？？

**Comment by GTX-GSO** [comment]
> 这个是你对这个issue的描述 摘录重点内容如下
> 
> > 先说结论，**被相关平台删除的贴子!=被中国政府和谐的内容**
> 
> > 换句话讲，**### 国内**的网络审查主要体现在**立项审查**上，具体细化到执行方面比较类似于大家都接触过的域名备案，而对于舆论事件的审查主要依赖于被动监测，即互联网媒体平台提供方通报、工信部12377.cn举报，不会也没有能力进行多平台大范围的舆论筛查。
> 
> > 而大多数的删帖、控评、限流等网站内容筛查**本质是一种资本的自保行为**，多采用算法+平台内举报+人工的模式对敏感内容即时甄别与排除。
> 
> > 所以把### **国内**过于严苛的内容筛查并归结于政府的和谐是不恰当的，我支持端点星项目的出发点与积极意义，但我更希望它能像WIKI一样客观中立不带政治倾向，也希望你们可以选择更为恰当的表述
> 
> 概括一下就是我上文反驳的观点 即 **删除文章和政府无关 是平台行为**
> 
> 之后的讨论我想也应该围绕这点
> 
> 如果你还想另外讨论端点星是怎么没的 可以另开一个issue

帮你标注了国内两个字以防你看不到，你是想说github也属于国内平台受国家监管吗？？
另外如果这是中国特有的行为，那么希望你能解释下tw fb大量删除大陆账号 ytb对中国positive视频标注红叉限流限推广后台锁定播放量订阅量又是什么行为，是邪恶的中国政府秘密雇佣hacker采用了高端的SQL注入欧美大厂数据库自导自演对吗？

**Comment by larvata** [comment]
我自始至终都是谈论的国内网站
所以当你扯到端点星怎么没的我还建议你另开issue
