### ISSUE TITLE
中央表态：三峡大坝有问题，各方正全力寻求解决方案

### ISSUE THREAD

**Issue by cmmei** [Terminus2049/Terminus2049.github.io#65]
https://www.xuehua.us/2018/05/27/%E4%B8%AD%E5%A4%AE%E8%A1%A8%E6%80%81%EF%BC%9A%E4%B8%89%E5%B3%A1%E5%A4%A7%E5%9D%9D%E6%9C%89%E9%97%AE%E9%A2%98-%E5%90%84%E6%96%B9%E6%AD%A3%E5%85%A8%E5%8A%9B%E5%AF%BB%E6%B1%82%E8%A7%A3%E5%86%B3%E6%96%B9/

财联社：https://www.cailianpress.com/depth/244733

**Comment by b614103080** [comment]
幹
