### ISSUE TITLE
快讯 | 人民大学经济学院顾姓教授已被取消教师资格！

### ISSUE THREAD

**Issue by cmmei** [Terminus2049/Terminus2049.github.io#7]
https://archive.is/cNXZh

顾被取消教师资格的消息不知是否可靠。

但这篇是删了。

**Comment by b614103080** [comment]
匿名消息，觉得可以等等。如果真的取消资格，这几天应该会有更正式的消息发布。

**Comment by tsai1993** [comment]
基本可以发了，Terminus 并不保证文章的内容真实，这是由读者来判断的，Terminus 保证的是文章的可获得性。
