### ISSUE TITLE
烧伤超人阿宝：对不起，我们输了

### ISSUE THREAD

**Issue by b614103080** [Terminus2049/Terminus2049.github.io#76]
只找到圖片：https://i.imgur.com/9MrOk25.jpg

**Comment by cmmei** [comment]
https://www.wxnmh.com/thread-3341636.htm 搜到了。

**Comment by cmmei** [comment]
https://chinadigitaltimes.net/chinese/2018/06/%E7%83%A7%E4%BC%A4%E8%B6%85%E4%BA%BA%E9%98%BF%E5%AE%9D%EF%BC%9A%E5%AF%B9%E4%B8%8D%E8%B5%B7%EF%BC%8C%E6%88%91%E4%BB%AC%E8%BE%93%E4%BA%86%E3%80%82/

**Comment by b614103080** [comment]
OK，已完成備份
