### ISSUE TITLE
Supchina的报道

### ISSUE THREAD

**Issue by b614103080** [Terminus2049/Terminus2049.github.io#9]
https://supchina.com/2018/04/26/yue-xin-back-at-school-surveillance-cameras-up-on-peking-university-campus/

**Comment by cmmei** [comment]
https://webcache.googleusercontent.com/search?q=cache:DoBCgWsuf6wJ:https://www.qdaily.com/articles/52934.html+&cd=1&hl=ja&ct=clnk&gl=jp

**Comment by cmmei** [comment]
Google cache
